"""Prepare attributed, source-only teaching packages; never alter supplied originals."""
from pathlib import Path
import re, shutil, zipfile, json, hashlib, difflib
SRC=Path(r'F:\UbuntuShareFolder\BasicOFProgramming')
WORK=Path(r'F:\UbuntuShareFolder\.foamlab-build\programming\sources')
OUT=Path(r'E:\Hexo\source-openfoam\downloads\programming')
OUT.mkdir(parents=True,exist_ok=True)
WORK.mkdir(parents=True,exist_ok=True)

def allowed(rel):
    parts=rel.parts
    if any(p.startswith(('processor','linux64','darwin','win64')) or p in ('lnInclude','postProcessing','VTK','.git','polyMesh','dynamicCode') for p in parts): return False
    if 'testCase' in parts:
        i=parts.index('testCase')
        if len(parts)>i+1 and re.fullmatch(r'[0-9]+(?:\.[0-9]+)?',parts[i+1]) and parts[i+1]!='0': return False
    if rel.name.startswith(('log.','log_')) or rel.suffix.lower() in ('.o','.so','.dep','.vtk','.vtu','.vtp','.vtm','.mp4','.foam','.openfoam'): return False
    if rel.name in ('result','customOutputFile.dat'): return False
    return True

roots=sorted(SRC.glob('OFtutorial*'))
for root in roots:
    dst=WORK/root.name; dst.mkdir(exist_ok=True)
    for f in root.rglob('*'):
        if f.is_file() and allowed(f.relative_to(root)):
            p=dst/f.relative_to(root); p.parent.mkdir(parents=True,exist_ok=True); shutil.copy2(f,p)
    shutil.copy2(SRC/'LICENSE',dst/'LICENSE')
    for f in dst.rglob('*'):
        if f.is_file() and f.name in ('blockMeshDict','controlDict'):
            s=f.read_text(); s=s.replace('convertToMeters','scale').replace('writeCompression           uncompressed','writeCompression           off'); f.write_text(s,newline='\n')
    attribution=f'''# FoamLab teaching copy: {root.name}

Original project: Basic OpenFOAM Programming Tutorials, Artur K. Lidtke (2017–2021) and contributors, including Ramkumar (tutorials 13, 14, 16).
Source supplied by the site owner from BasicOFProgramming. Original copyright headers and GPL-3.0-or-later licence are retained.

This is a source-only educational distribution prepared for OpenCFD OpenFOAM v2512 on 2026-10-02. It excludes compiled objects, shared libraries, solution time directories, processor data and generated meshes. Original demonstration images are historical teaching output, not newly verified simulation results.

Load the v2512 environment, run `bash Allwmake`, then `cd testCase && bash Allrun`. Meshes are generated by the included dictionaries/scripts. If scripts are not executable after extraction, run `chmod u+x All*` in the tutorial and case directories.

See `/read/?slug=programming-{int(root.name[10:12]):02d}` on the FoamLab website for the Chinese explanation and precise verification scope. Successful compilation is not evidence of numerical or physical validation. Original notes can contain legacy version headers; the site explains relevant API changes.

Distribution edits: legacy `convertToMeters` becomes `scale`; obsolete compression setting becomes `off`. Tutorial 08 uses the v2512 field writeEntry member signature. Tutorial 12 is ported from Foundation fvModel/fvModels to OpenCFD fv::option/fvOptions, includes parameter validation, and uses the projected upstream velocity. No external dependencies or credentials are included.
'''
    (dst/'FOAMLAB-README.md').write_text(attribution,encoding='utf-8')

d=WORK/'OFtutorial08_customBC'
p=d/'prescribedPipeInletFvPatchVectorField.C'; s=p.read_text().replace('writeEntry(os, "value", *this);','writeEntry("value", os);'); p.write_text(s,newline='\n')

d=WORK/'OFtutorial12_momentumSource'
for name in ('customActuationDiskSource.H','customActuationDiskSource.C'):
    p=d/name; s=p.read_text().replace('"fvModel.H"','"fvOption.H"').replace('public fvModel','public option').replace('fvModel,','option,').replace('fvModel::read(dict)','option::read(dict)').replace('fvModel(name, modelType, mesh, dict)','option(name, modelType, dict, mesh)').replace('coeffs(dict)','coeffs_')
    s=re.sub(r'const fvMesh& mesh,\s*const dictionary& dict', 'const dictionary& dict,\n    const fvMesh& mesh',s)
    s=re.sub(r'const word& fieldName\s*\) const','const label fieldi\n) ',s)
    s=s.replace('virtual wordList addSupFields() const;','// fv::option uses fieldNames_ and resetApplied().')
    s=re.sub(r'Foam::wordList Foam::fv::customActuationDiskSource::addSupFields\(\) const\s*\{.*?\}\s*','',s,flags=re.S)
    if name.endswith('.C'):
        s=s.replace('    // Locate the upstream cell used', '    fieldNames_ = wordList(1, Uname_);\n    resetApplied();\n    if (D_ <= SMALL || t_ <= SMALL || mag(diskDir_) <= SMALL || Ct_ <= SMALL || Cp_ <= SMALL || Cp_ >= Ct_)\n    {\n        FatalErrorInFunction << "Require D>0, thickness>0, nonzero diskDir and 0<Cp<Ct" << exit(FatalError);\n    }\n\n    // Locate the upstream cell used')
        s=s.replace('vectorField rHat ((mesh.C() - x0) / mag(mesh.C() - x0));','vectorField displacement(mesh.C() - x0);')
        s=s.replace('R[cellI] * (rHat[cellI] & diskDir_)','displacement[cellI] & diskDir_').replace('sqrt(pow(R[cellI], 2.) - pow(dNormal, 2.))','sqrt(max(sqr(R[cellI]) - sqr(dNormal), scalar(0)))')
        s=s.replace('    // validate inputs\n    checkData();','    // validate inputs\n    checkData();\n    if (V_ <= VSMALL) FatalErrorInFunction << "No cells selected; increase disk thickness" << exit(FatalError);')
    p.write_text(s,newline='\n')
p=d/'customActuationDiskSourceTemplates.C'; s=p.read_text(); s=s.replace('upU *= (upU/mag(upU)) & (-1.*diskDir_);','upU = (upU & diskDir_) * diskDir_;'); s=s.replace('<< T << nl << endl;','<< T*mag(upU) << nl << endl;'); p.write_text(s,newline='\n')
p=d/'testCase/constant/fvModels'; s=p.read_text().replace('object      fvModels;','object      fvOptions;'); s=s.replace('    upstreamPoint','    active yes;\n    customActuationDiskSourceCoeffs\n    {\n    upstreamPoint').replace('    Uname U;','    Uname U;\n    }'); (p.parent/'fvOptions').write_text(s,newline='\n'); p.unlink()
p=d/'Make/options'; p.write_text('EXE_INC = \\\n    -I$(LIB_SRC)/finiteVolume/lnInclude \\\n    -I$(LIB_SRC)/meshTools/lnInclude\n\nLIB_LIBS = \\\n    -lfiniteVolume \\\n    -lmeshTools\n',newline='\n')

d=WORK/'OFtutorial05_basicParallelComputing';p=d/'OFtutorial5.C';s=p.read_text().replace('#include "fvCFD.H"','#include "fvCFD.H"\n#include "processorPolyPatch.H"');p.write_text(s,newline='\n')
d=WORK/'OFtutorial09_runtimePostprocessingUtility';p=d/'pipeCalc.C';s=p.read_text().replace('file(i)','files(i)').replace('file(MAIN_FILE)','files(MAIN_FILE)').replace('file() << endl','files(MAIN_FILE) << endl');s=s.replace('resetNames(createFileNames(dict));','resetNames(createFileNames(dict));\n    if (Pstream::master()) writeFileHeader(MAIN_FILE);');p.write_text(s,newline='\n')
d=WORK/'OFtutorial11_modifyingTheMesh';p=d/'OFtutorial11.C';s=p.read_text().replace('clone(points),','pointField(points),').replace('word defaultFacesType = emptyPolyPatch::typeName;','word defaultFacesType("patch");');p.write_text(s,newline='\n')
p=d/'testCase/Allclean';s=p.read_text().replace('rm -r ','rm -rf ');p.write_text(s,newline='\n')
d=WORK/'OFtutorial15_discretisation';p=d/'testCase/system/controlDict';s=p.read_text().replace('type    lineCell;','type    cellCentre;');p.write_text(s,newline='\n')

changes={5:'Explicitly include processorPolyPatch.H.',8:'Use the v2512 member writeEntry("value", os) signature.',9:'Use logFiles::files(index) and explicitly write the header after file creation.',11:'Pass pointField(points) to the v2512 mesh constructor; use a 3-D patch for default faces; allow missing generated paths when cleaning. The toy 5-cell mesh still fails the underdeterminedCells quality check and is not a production mesh.',12:'Port Foundation fvModel/fvModels to OpenCFD fv::option/fvOptions; validate input, avoid division by zero in cell selection and project upstream velocity onto the disk normal.',15:'Replace removed lineCell sampling type with cellCentre.'}
for root in roots:
    dst=WORK/root.name;n=int(root.name[10:12]); patch=[]
    for f in dst.rglob('*'):
        rel=f.relative_to(dst); old=root/rel
        if f.is_file() and old.is_file() and f.suffix.lower() not in ('.png','.pdf','.pvsm'):
            try:
                a=old.read_text().splitlines(True);b=f.read_text().splitlines(True)
            except UnicodeError:continue
            if a!=b:patch.extend(difflib.unified_diff(a,b,fromfile='original/'+rel.as_posix(),tofile='v2512/'+rel.as_posix()))
    (dst/'MIGRATION.patch').write_text(''.join(patch),encoding='utf-8')
    with (dst/'FOAMLAB-README.md').open('a',encoding='utf-8') as out:
        out.write('\nSpecific compatibility edits: '+changes.get(n,'Only common dictionary keyword cleanup where needed.')+'\n')
    if n==11:
        with (dst/'README.md').open('a',encoding='utf-8') as out:out.write('\n## FoamLab verification correction\nThe current 5-cell demonstration compiles and writes a mesh on v2512, but full checkMesh reports one failed underdeterminedCells quality check. It must not be described as a valid production mesh.\n')

def archive_all():
    manifest=[]
    for root in sorted(WORK.glob('OFtutorial*')):
        path=OUT/(root.name+'-v2512.zip')
        with zipfile.ZipFile(path,'w',zipfile.ZIP_DEFLATED) as z:
            for f in sorted(root.rglob('*')):
                if f.is_file() and allowed(f.relative_to(root)):
                    info=zipfile.ZipInfo((Path(root.name)/f.relative_to(root)).as_posix()); info.external_attr=(0o100755 if f.name.startswith('All') else 0o100644)<<16; info.compress_type=zipfile.ZIP_DEFLATED
                    z.writestr(info,f.read_bytes())
        manifest.append(dict(tutorial=root.name,path='/downloads/programming/'+path.name,size=path.stat().st_size,sha256=hashlib.sha256(path.read_bytes()).hexdigest()))
    (OUT/'manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2),encoding='utf-8')
    return manifest
if __name__=='__main__': print(json.dumps(archive_all(),indent=2))
