"""Reviewed examples and context for individual functionObject reference entries."""
from pathlib import Path
import json,re
P=Path(__file__).resolve().parent
profiles=json.loads((P/'profiles.json').read_text(encoding='utf-8'))
def config(name,body,lib='fieldFunctionObjects',origin=''):
    profiles[name]['code']=name+'Example\n{\n    type '+name+';\n    libs ('+lib+');\n'+body.strip()+'\n}'
    profiles[name]['origin']=origin or '按 v2512 接口配置'
    profiles[name]['tested']=False
def explain(name,text,description=None):
    profiles[name]['explanation']=text
    if description:profiles[name]['description']=description
def variant(name,title,patch,text):
    profiles[name]['variants'].append(dict(title=title,patch=patch,explanation=text))
# Do not accumulate examples when this editorial script is rerun.
for p in profiles.values():p['variants']=[]

config('parProfiling','    detail 0;\n    executeControl onEnd;\n    writeControl none;','utilityFunctionObjects')
config('writeDictionary','    dictNames (controlDict fvSchemes fvSolution);\n    writeControl writeTime;','utilityFunctionObjects')
config('removeRegisteredObject','    objects (temporarySpeed);','utilityFunctionObjects')
config('ensightCloud','    clouds (kinematicCloud);\n    fields (U d);\n    format binary;\n    writeControl writeTime;','lagrangianFunctionObjects')
config('icoUncoupledKinematicCloud','    U U;\n    kinematicCloud kinematicCloud;','lagrangianFunctionObjects')
config('phaseForces','    phase air;\n    writeControl writeTime;','phaseFunctionObjects')
config('resolutionIndex','    model CelikNuIndex;\n    result LESIndex;\n    writeControl writeTime;')
config('hydrostaticPressure','    p_rgh p_rgh;\n    ph_rgh ph_rgh;\n    rho rho;\n    U U;\n    nCorrectors 5;\n    reInitialise true;','initialisationFunctionObjects')
config('radiometerProbes','    probeLocations ((0.5 0.5 0.5));\n    probeNormals ((0 0 1));\n    writeControl timeStep;\n    writeInterval 10;','utilityFunctionObjects')
config('viewFactorHeatFlux','    qr qr;\n    writeControl writeTime;')
config('coded','    name reportTime;\n    codeExecute\n    #{\n        Info<< "Time = " << mesh().time().value() << nl;\n    #};','utilityFunctionObjects')
config('setTimeStep','    deltaT 0.005;','utilityFunctionObjects')
config('systemCall','    master true;\n    executeCalls ("echo FoamLab-execute");\n    writeCalls ("echo FoamLab-write");\n    endCalls ("echo FoamLab-end");','utilityFunctionObjects')
profiles['binField']['code']=profiles['binField']['code'].replace('${../forceCoeffs1/CofR}','(0.007 0 0.004)')
profiles['bladeForces']['code']=profiles['bladeForces']['code'].replace('fieldsInteval','fieldsInterval')
# A scalar speed from mag(U) is already produced by the supplied cavity example.
explain('mag','把速度向量 U 转换为标量速度大小。field U 指定输入，result speed 指定输出名；保存后在 ParaView 中选择 speed 即可查看速度云图。')
explain('magSqr','以 U 为输入时，结果为速度大小的平方，量纲是 m²/s²。它常作为单位质量动能的中间量，动能还需要乘以 0.5。')
explain('grad','标量的梯度是向量，向量的梯度是二阶张量。本例读取 U 并生成 gradU，梯度离散采用 fvSchemes 中对应的 gradSchemes 设置。')
explain('div','本例输入面通量 phi，计算各单元的净流出通量除以单元体积。输出 divPhi 可用于观察局部连续性误差；它的物理量纲随 phi 的定义变化。')
explain('vorticity','对 U 求旋度，得到三分量涡量场，单位通常为 s⁻¹。在 ParaView 中既可查看涡量模，也可查看与二维流动平面垂直的分量。')
explain('enstrophy','根据 U 的旋度计算 0.5 倍涡量模平方。它是标量场，适合观察旋转强度的空间分布。')
explain('LambVector','计算涡量与速度的叉积，得到向量场。先由 U 求涡量，再与同一速度场组合，适合分析旋涡与输运之间的关系。')
explain('Q','由速度梯度的旋转部分和应变部分计算 Q。可在 ParaView 中对正 Q 值建立等值面，观察旋转占优区域。')
explain('Lambda2','由速度梯度构造对称矩阵并取其中间特征值。常用负 Lambda2 等值面显示涡结构，等值面阈值应结合流动速度和长度尺度选择。')
explain('flowType','比较速度梯度中旋转与应变的强度。输出通常从旋转占优的负值过渡到应变占优的正值，简单剪切对应两者接近的情况。')
explain('components','把向量或张量拆成若干标量场。输入 U 时可得到 Ux、Uy、Uz，便于分别绘制各方向速度的剖面。')
explain('add','fields 按列表指定参与相加的场，输入场采用相同量纲与兼容类型。本例 U 与自身相加，结果 twoU 是原速度的两倍。')
explain('subtract','按 fields 中的顺序，用第一个场依次减去后续场。本例用同一个场相减得到零场，可先确认输入与输出名称，再换成两组需要比较的结果。')
explain('multiply','按 fields 的列表组合相乘。输出场的类型和量纲由输入决定；标量系数场与向量场相乘可用于空间加权。')
explain('surfaceInterpolate','fields 中每一项都是输入、输出名称对。把单元中心的场插值到网格面上，结果保留为 surfaceField，适合后续通量计算。')
explain('exprField','用表达式创建一个命名场。本例的 0.5*magSqr(U) 计算单位质量动能，dimensions 指定其量纲，field 指定输出文件名。')
explain('probes','在固定坐标连续记录速度和压力。本例的两个点位于边长 0.1 m 的方腔内部，z=0.005 m 位于薄层中面；每个字段的文件按时间排列，每列对应一个探针。')
variant('probes','只记录压力',{'fields':'(p)'},'保留原探针位置，只保存压力时序。fields 控制采样变量，减少字段也会减少输出文件。')
variant('probes','沿方腔中线布置三个探针',{'probeLocations':'((0.05 0.025 0.005) (0.05 0.05 0.005) (0.05 0.075 0.005))','interpolationScheme':'cellPoint'},'三个点具有相同 x、z 坐标，沿 y 方向排列。cellPoint 用单元与顶点信息插值，便于比较同一条线上的流速变化。')
explain('patchProbes','把探针位置投影到所选边界上并记录边界场值。本例 patches 选方腔的 movingWall，探针位于顶壁；这适合记录壁面压力，而域内测点使用 probes。')
variant('patchProbes','只记录顶壁压力',{'fields':'(p)'},'测点和 movingWall 保持一致，只输出边界压力。')
variant('patchProbes','保存每步采样值供后续对象读取',{'sampleOnExecute':'true','executeControl':'timeStep','executeInterval':'1'},'除了写出阶段，也在执行阶段更新内存中的采样值。依赖探针结果的后续功能对象应排在它后面。')
explain('sets','沿给定点集采样。配置中的 start、end 决定采样线位置，nPoints 决定点数；输出文件第一列是 axis 指定的坐标或距离，后续列是场值。')
variant('sets','以 CSV 保存剖面',{'setFormat':'csv'},'保持原采样点不变，改为逗号分隔的数据文件，便于导入表格或绘图程序。')
variant('sets','同时采样压力和速度',{'fields':'(p U)','interpolationScheme':'cellPoint'},'在同一组采样位置上保存 p 与 U，方便将压力变化和速度剖面对照。')
explain('surfaces','在指定几何表面上提取场。本例从溃坝的 alpha.water=0.5 等值面提取水气界面，并在该表面采样 U、p_rgh；surfaceFormat vtk 便于用 ParaView 打开。')
variant('surfaces','只导出界面速度',{'fields':'(U)'},'保留同一水气界面，只输出速度，减小每个时间目录的数据量。')
variant('surfaces','改用 EnSight 表面输出',{'surfaceFormat':'ensight'},'几何选择保持不变，改变结果的文件格式，适合统一到 EnSight 数据处理流程。')
explain('fieldMinMax','逐次记录所选场的最小值和最大值。本例监测 alpha.water，可从输出中查看相分数的取值范围；对于向量场，mode 决定按模还是按分量比较。')
variant('fieldMinMax','同时监测相分数和速度',{'fields':'(alpha.water U)','mode':'magnitude'},'速度按模比较，输出最大速度所在位置；相分数仍按标量统计。')
variant('fieldMinMax','仅保存极值而省略坐标',{'location':'false'},'当只需要绘制极值随时间变化的曲线时，可以缩短每行输出。')
explain('volFieldValue','本例在整个热房间区域统计 T 的体积加权平均值。volAverage 使大小不同的单元按各自体积贡献权重，结果可直接作为域平均温度。')
variant('volFieldValue','查看最高温度',{'operation':'max'},'同样选择全部单元，但改为找 T 的最大值，用于监测局部热点。')
variant('volFieldValue','计算温度的体积积分',{'operation':'volIntegrate'},'得到各单元 T×体积的总和，单位为 K·m³。除以总体积后即为体积平均温度；计算热量还需要密度和比热。')
explain('surfaceFieldValue','本例对 pitzDaily 的 inlet 面通量 phi 求和。phi 已包含面面积，因此 sum 给出总流量；入口法向朝外，流入通常表现为负值。')
variant('surfaceFieldValue','监测出口流量',{'name':'outlet'},'将统计边界改为 outlet。对照入口和出口的总流量可以检查质量或体积收支。')
variant('surfaceFieldValue','计算入口平均压力',{'fields':'(p)','operation':'areaAverage'},'压力是面上的强度量，使用面积加权平均。areaAverage 与对已积分面通量求和是两种不同的操作。')
explain('multiFieldValue','在一个对象中先完成多个区域统计，再组合这些数值。本例分别求入口和出口的面积平均压力，随后相减得到压降；子对象次序决定相减顺序。')
variant('multiFieldValue','计算两侧均值之和',{'operation':'add'},'先得到两个区域的平均值，再相加。输入是子对象的统计结果，而非逐单元的压力场。')
variant('multiFieldValue','比较两侧均值的比值',{'operation':'divide'},'按子对象顺序计算比值，适合比较具有相同量纲且分母远离零的监测量。压力接近零时，优先采用压差。')
explain('fieldStatistics','一次配置输出多个空间统计量。本例分别统计 p 和 U 的 min、max、mean、variance，mode component 对向量按分量处理，mean volumetric 采用体积权重。')
variant('fieldStatistics','只统计平均值与方差',{'statistics':'(mean variance)'},'去掉极值列，重点观察空间平均水平及离散程度。这里的方差是空间统计量。')
variant('fieldStatistics','按速度大小统计',{'fields':'(U)','mode':'magnitude'},'把每个速度向量先转成大小，再统计其空间分布，得到的量与逐分量统计不同。')
explain('histogram','将标量值按区间分箱。这里用已由 mag(U) 创建的 speed，0 到 1 m/s 分成 10 箱；把 speed 的生成对象放在 histogram 前面。')
variant('histogram','加密速度分箱',{'nBins':'20'},'统计范围不变，把箱宽从 0.1 m/s 缩小到 0.05 m/s，以观察更细的速度分布。')
variant('histogram','关注低速区域',{'min':'0','max':'0.2','nBins':'10'},'只统计 0 到 0.2 m/s 的速度段，用较细的区间观察回流区和近壁低速单元。')
explain('fieldAverage','按字段分别累积时间平均和二阶脉动矩。本例从 0.1 s 开始统计，U 同时生成 UMean 和 UPrime2Mean，p 只生成 pMean。base time 使可变时间步按实际时长加权。')
variant('fieldAverage','重启时重新开始平均',{'restartOnRestart':'true'},'适合把本次重启后的计算当成新的统计阶段；此前保存的累计时间不会继续合并到新平均中。')
variant('fieldAverage','每次输出后重新统计',{'restartOnOutput':'true'},'按相邻两次输出之间的时间段分别求平均，可比较不同时段的流动。')
explain('valueAverage','对另一个功能对象已经输出的数值继续做时间平均。functionObject 选数据来源，fields 写该对象的结果键，示例 average(p) 是区域压力平均值。')
variant('valueAverage','使用有限平均窗口',{'window':'0.1'},'以最近 0.1 个模拟时间单位的数据作为平均窗口，适合跟踪随时间缓慢变化的监测值。')
variant('valueAverage','重启后重新累积',{'resetOnRestart':'true'},'将重启后的监测值作为新的平均序列。')
explain('forces','对指定壁面的压力和黏性应力积分，分别输出合力与关于 CofR 的力矩。本例选择 pitzDaily 上、下壁面，rho rhoInf 和 rhoInf 1 将运动压力换算为实际力。')
variant('forces','只统计下壁面',{'patches':'(lowerWall)'},'将受力表面缩小到下壁面，其余密度和参考中心保持一致，便于比较不同壁面的贡献。')
variant('forces','更换力矩参考中心并保存受力场',{'CofR':'(0.1 0 0)','writeFields':'true'},'合力与参考中心无关，力矩会随参考中心改变。writeFields 同时保存空间分布，便于观察哪些位置贡献较大。')
explain('forceCoeffs','把压力和黏性载荷转换为无量纲系数。力系数的分母使用 0.5×rhoInf×magUInf²×Aref；力矩系数还要乘参考长度 lRef。参考值应对应所研究物体及来流。')
variant('forceCoeffs','只计算下壁面的系数',{'patches':'(lowerWall)'},'保持相同参考速度、面积和长度，单独比较下壁面对载荷系数的贡献。')
variant('forceCoeffs','保存系数对应的场',{'writeFields':'true'},'在总体系数之外保存空间分布，便于分析压力与黏性贡献的位置。')
explain('pressure','进行压力形式的转换。本例 mode static 配 rho rhoInf，把不可压缩求解器的运动压力转为实际静压；result pPa 指定输出名。')
variant('pressure','计算总压',{'mode':'total','result':'pTotal'},'在静压基础上加入速度对应的动压，适合比较管道或扩压段的总压损失。')
variant('pressure','采用水的参考密度',{'rhoInf':'1000','result':'pWater'},'相同运动压力乘以 1000 kg/m³，得到以水的密度换算的实际压力。参考密度应与物理问题一致。')
explain('yPlus','根据壁距、速度梯度和湍流模型计算 y+。在 pitzDaily 湍流算例中，输出既包括壁面场，也包括最小、最大和平均值，便于检查首层网格位置。')
variant('yPlus','直接由流场计算 y+',{'useWallFunction':'false'},'改用场变量计算 y+，可以与壁面函数给出的值进行对照。')
variant('yPlus','只保留统计文本',{'writeFields':'false'},'适合长时间计算中监测 y+ 的范围，减少完整壁面场文件。')
explain('wallShearStress','从动量输运模型取得壁面剪切应力。本例选择壁面，结果可用于识别低剪切或剪切方向改变的区域；不可压缩模型中的输出可能采用运动应力量纲。')
variant('wallShearStress','只检查下壁面',{'patches':'(lowerWall)'},'保留研究对象对应的壁面数据，便于提取回流区附近的剪切应力。')
variant('wallShearStress','只保存统计信息',{'writeFields':'false'},'保留监测输出，减少每个时刻的场文件。')
explain('turbulenceFields','把湍流模型内部计算的量保存为可读场。pitzDaily 使用的模型提供 k、epsilon、nut 等量；fields 选择要提取的字段，prefix 用于区分来源。')
variant('turbulenceFields','只保存 k 和 nut',{'fields':'(k nut)'},'用湍动能和湍流黏度观察模型作用最强的区域。')
variant('turbulenceFields','给输出增加独立前缀',{'prefix':'myTurbulence'},'生成的场名称带 myTurbulence 前缀，避免与原来的求解字段混淆。')
explain('wallHeatFlux','从传热模型计算壁面热流密度。本例 model wall 用于热房间壁面，输出各壁面的最小值、最大值和面积积分；热流积分可用于比较壁面的净传热。')
variant('wallHeatFlux','只统计地板',{'patches':'(floor)'},'把热流统计限制在供热地板上，积分值对应该边界的总传热率。')
variant('wallHeatFlux','同时比较地板和顶板',{'patches':'(floor ceiling)'},'在同一输出频率下对照两个边界的热流，观察热量进入与离开房间的过程。')
explain('heatTransferCoeff','根据壁面热流与参考温差计算换热系数。本例 field T 读取温度，localReferenceTemperature 采用局部参考温度，结果 htc 用于观察不同壁面的换热强弱。')
variant('heatTransferCoeff','只分析地板换热',{'patches':'(floor)'},'供热壁面单独输出，便于绘制换热系数沿壁面的分布。')
variant('heatTransferCoeff','单独输出顶板结果',{'patches':'(ceiling)','result':'ceilingHtc'},'选择顶板并使用新的场名，方便与地板结果并列查看。')
explain('interfaceHeight','沿给定方向积分相分数，得到等效液位。本例 alpha.water 表示水相，direction 指向重力方向；locations 指定水平位置，适合比较不同位置的液位变化。')
variant('interfaceHeight','只保留一个液位测点',{'locations':'((0.2 0 0.073))'},'在溃坝区域内选一个水平位置，得到一条液位时序。坐标的竖直分量应结合该算例的方向设置理解。')
variant('interfaceHeight','增加液位测点',{'locations':'((0.2 0 0.073) (0.4 0 0.073))'},'在相同竖直方向上比较两个水平位置，观察波前通过时的先后变化。')
explain('solverInfo','记录每个字段在线性求解中的初始残差、最终残差、迭代次数等信息。fields (p U) 同时监测压力和速度，可用这些数据检查代数求解过程。')
variant('solverInfo','只跟踪压力方程',{'fields':'(p)'},'减少日志中的字段数量，重点检查压力校正的收敛情况。')
variant('solverInfo','输出残差分布场',{'writeResidualFields':'true'},'除整体残差数值外，还保存初始残差的空间分布，帮助定位误差较大的单元。')
explain('CourantNo','由面通量计算局部 Courant 数，输出 Co 场。查看其最大值和空间分布可以确定较大时间步主要影响了哪些单元。')
explain('continuityError','用面通量 phi 统计局部、全局和累计连续性误差。把全局误差与入口、出口流量放在一起看，可以检查计算中的收支变化。')
explain('vtkWrite','把指定体场和边界数据直接写成 VTK。本例同时导出 U、p 和已计算的 speed，目录结构由对象名和时间决定，可直接在 ParaView 中打开。')
variant('vtkWrite','只导出内部压力场',{'fields':'(p)','boundary':'false','internal':'true'},'保留单元内部压力，省去边界数据，适合只需要内部剖面分析的情况。')
variant('vtkWrite','以二进制保存顶点插值结果',{'format':'binary','interpolate':'true'},'二进制格式减少文本体积；顶点插值便于某些可视化操作，同时保留其与原单元值的区别。')
explain('ensightWrite','按 EnSight 格式输出选定字段。本例 fields (U p) 选择速度和压力，format ascii 便于直接检查文件内容。')
variant('ensightWrite','使用二进制输出',{'format':'binary'},'数据量较大时采用二进制编码，保持相同字段与输出时刻。')
variant('ensightWrite','只输出内部速度',{'fields':'(U)','boundary':'false'},'减少导出范围，方便单独处理流场内部的速度分布。')
explain('readFields','把时间目录中的场读入内存。需要后处理的字段不由当前求解器主动创建时，可先放一个 readFields 对象，再放依赖这些场的运算对象。')
variant('readFields','读取压力与速度',{'fields':'(p U)'},'后续对象可以在对象数据库中找到这两个场。')
variant('readFields','延后到执行阶段读取',{'readOnStart':'false'},'对象构造时暂不读取，待执行阶段再载入，适合数据由更早的步骤准备的流程。')
explain('writeCellCentres','将单元中心坐标保存为 C 以及各坐标分量。它适合检查网格位置，或与速度、温度等场一起导出后进行空间筛选。')
explain('writeCellVolumes','将各单元体积保存为 V 场。可用于观察网格尺寸变化，也可作为后续积分或加权统计的数据。')
explain('processorField','输出每个单元所属的并行进程编号。串行运行时编号一致；并行运行并重构结果后，可在 ParaView 中查看分区边界。')
explain('timeInfo','记录 CPU 时间和实际运行时间。perTimeStep 决定保存累计耗时还是本步耗时，便于比较网格或功能对象设置对运行速度的影响。')
variant('timeInfo','记录每一步耗时',{'perTimeStep':'true'},'观察某些计算步骤是否明显变慢，适合检查网格更新或输出文件带来的耗时。')
variant('timeInfo','只在结束时汇总',{'perTimeStep':'false','writeControl':'onEnd'},'保留最终累计耗时，适合批量比较多个算例。')
explain('runTimeControl','按 conditions 中的条件控制计算。示例用 maxDuration 限定该对象经历的模拟时间，并在条件满足后写出结果、结束运行；其他条件可监测残差或场统计值。')
variant('runTimeControl','条件满足后只报告',{'satisfiedAction':'none'},'保留条件判断和记录，便于先观察触发时刻。')
variant('runTimeControl','结束前连续保存两步',{'nWriteStep':'2'},'满足条件后继续保存两个时间步，使结束阶段留有相邻时刻的数据。')
explain('setTimeStep','用 deltaT 指定求解器下一步采用的时间步长。该值可写成常量，也可使用随时间变化的 Function1；放入算例后由运行中的求解器调用。')
variant('setTimeStep','把时间步减半',{'deltaT':'0.0025'},'对相同流场和网格，时间步减半也会相应降低对流 Courant 数，同时增加推进相同时长所需的步数。')
variant('setTimeStep','分阶段改变时间步',{'deltaT':'table ((0 0.001) (0.1 0.005) (1 0.005))'},'启动阶段从较小时间步开始，随后按表格插值过渡到 0.005；时间点采用模拟时间。')
explain('abort','运行时检查一个外部文件是否存在；发现文件后按 action 停止计算。对象名为 ABORT 且采用默认路径时，可在算例目录执行 touch ABORT 触发停止。')
variant('abort','触发后立即写出并停止',{'action':'writeNow'},'适合需要尽快保存当前状态并结束的情况。')
variant('abort','指定单独的停止文件',{'file':'"<case>/STOP"','action':'nextWrite'},'在算例目录创建 STOP 后，求解器等到下一次计划写出再结束。')
explain('parProfiling','统计 MPI 通信等并行活动的耗时。示例在结束时执行统计，writeControl none 表示不另设周期写出；在并行求解时使用更有意义。')
variant('parProfiling','增加统计详细程度',{'detail':'1'},'查看更详细的通信统计，便于分析进程之间的等待与通信开销。')
variant('parProfiling','每 100 步报告一次',{'executeControl':'timeStep','executeInterval':'100'},'持续观察计算过程中的并行开销，而不是仅查看结束时的汇总。')
explain('writeDictionary','将指定字典写入日志，以便同时保留计算使用的设置。dictNames 可以选择 controlDict、fvSchemes 和 fvSolution，字典变化后可再次输出。')
variant('writeDictionary','只记录离散设置',{'dictNames':'(fvSchemes)'},'用于比较不同离散格式的运行日志。')
variant('writeDictionary','记录求解和时间控制',{'dictNames':'(fvSolution controlDict)'},'把线性求解容差与时间控制保存在同一份日志中。')
explain('removeRegisteredObject','从内存中的对象数据库移除指定对象。示例对象 temporarySpeed 应是前序步骤创建的临时量，移除之后其他对象将不再通过该名称读到它。')
variant('removeRegisteredObject','移除两个临时对象',{'objects':'(temporarySpeed temporaryGradient)'},'适合前序处理已经使用完多个中间结果的流程。')
variant('removeRegisteredObject','仅在计算结束时清理',{'executeControl':'onEnd'},'让临时对象在整个计算过程中可用，到结束阶段再移除。')
explain('coded','在功能对象接口中编译并执行一段 C++。name 给动态类命名，codeExecute 在执行阶段运行；本例只向日志写出当前模拟时间。')
variant('coded','每十步执行一次代码',{'executeControl':'timeStep','executeInterval':'10'},'将打印频率降为每十步一次，便于在日志中观察而不会每步重复输出。')
variant('coded','在指定时间段执行代码',{'timeStart':'0.1','timeEnd':'0.3'},'只在模拟时间 0.1 到 0.3 之间运行该对象，适合针对一个阶段添加诊断。')
explain('systemCall','在执行、写出和结束阶段调用外部命令。示例只打印三个阶段的标记，master true 使并行计算仅由主进程调用；启用外部调用需要相应的系统操作权限设置。')
variant('systemCall','仅在写出时运行',{'executeCalls':'()','endCalls':'()'},'保留 writeCalls，让外部命令与结果保存时刻对应。')
variant('systemCall','仅在结束时运行',{'executeCalls':'()','writeCalls':'()'},'用 endCalls 在计算结束后执行收尾操作。')
explain('resolutionIndex','计算 LES 网格解析程度指标。示例选择 CelikNuIndex，利用模型黏性与网格尺度相关量构造指标，适用于充分发展的湍流 LES 分析。')
variant('resolutionIndex','采用 Pope 指标',{'model':'PopeIndex','result':'PopeIndex'},'使用解析湍动能与总湍动能的关系，需要 UMean 等统计场；可先由 fieldAverage 保存平均速度。')
variant('resolutionIndex','采用耗散尺度指标',{'model':'CelikEtaIndex','result':'CelikEtaIndex'},'根据黏性与网格尺度构造另一种解析指标，用于与同一 LES 的黏性指标对照。')
explain('phaseForces','在 Euler 多相系统中输出所选相的作用力。phase 应与 phaseProperties 中的相名一致，示例选择 air；由相系统提供相间作用力模型。')
variant('phaseForces','选择水相',{'phase':'water'},'适用于相系统中存在 water 的气液算例；输出对应水相的模型作用力。')
variant('phaseForces','以固定步数输出',{'writeControl':'timeStep','writeInterval':'20'},'减少逐步场输出，同时保留作用力随计算变化的数据。')
explain('hydrostaticPressure','根据重力、密度与热物性模型建立静水平衡压力。适用于已经准备 p_rgh、ph_rgh 及相应边界的浮力算例，nCorrectors 指定压力校正次数。')
variant('hydrostaticPressure','增加压力校正次数',{'nCorrectors':'10'},'对密度与压力耦合较强的初始化，增加校正以进一步调整静水平衡。')
variant('hydrostaticPressure','延用已保存的初始化状态',{'reInitialise':'false'},'在具备已有初始化结果的重启算例中保留该状态。')
explain('radiometerProbes','模拟具有方向的辐射计探针。每个 probeLocation 对应一个 probeNormal，法向决定探针接收辐射的方向；算例需要提供该工具使用的辐射模型。')
variant('radiometerProbes','反向放置探针',{'probeNormals':'((0 0 -1))'},'测点位置不变，接收方向反向，可比较来自两侧的辐射。')
variant('radiometerProbes','同时放置两个定向探针',{'probeLocations':'((0.5 0.5 0.5) (0.5 0.5 0.8))','probeNormals':'((0 0 1) (0 0 1))'},'两个探针沿相同方向测量，对照不同空间位置的辐射强度。')
explain('viewFactorHeatFlux','汇总视角系数辐射模型的热流。算例先通过相应辐射设置生成 F 和 globalFaceFaces 数据，工具读取 qr 并按模型表面统计。')
variant('viewFactorHeatFlux','读取改名后的辐射热流场',{'qr':'qrRadiation'},'在算例将辐射热流字段命名为 qrRadiation 时使用该名称。')
variant('viewFactorHeatFlux','每十步记录辐射热流',{'writeControl':'timeStep','writeInterval':'10'},'用于观察辐射热流逐步趋于稳定的过程。')
explain('icoUncoupledKinematicCloud','在给定不可压缩流场中推进运动颗粒云。算例应备好 kinematicCloudProperties、粒子注入和物性设置；该对象使用已有 U 跟踪颗粒。')
variant('icoUncoupledKinematicCloud','使用另一组颗粒云',{'kinematicCloud':'tracerCloud'},'与 constant/tracerCloudProperties 中定义的颗粒云对应，可分别设置粒径和注入方式。')
variant('icoUncoupledKinematicCloud','使用平均速度追踪颗粒',{'U':'UMean'},'在已准备 UMean 场的算例中，以平均流动作为追踪速度，便于与瞬时流场结果比较。')
explain('ensightCloud','将拉格朗日颗粒云转换为 EnSight 输出。clouds 选择云，fields 选择颗粒属性；示例保留速度 U 和粒径 d。')
variant('ensightCloud','只导出颗粒直径',{'fields':'(d)'},'减少属性文件数量，适合只查看粒径的空间分布。')
variant('ensightCloud','以文本格式查看所有云',{'clouds':'(".*")','format':'ascii'},'匹配算例中的颗粒云，并以文本格式保存便于检查的属性值。')

(P/'profiles.json').write_text(json.dumps(profiles,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print('Authored contexts:',sum(bool(p['explanation']) for p in profiles.values()),'specific variants:',sum(len(p['variants']) for p in profiles.values()))
