const { chromium }=require('C:/Users/shark/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs');const path=require('node:path');const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');const out=path.join(root,'.openfoam-work');
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:1080}});const page=await context.newPage();let errors=[];page.on('pageerror',e=>errors.push(e.message));
 const origin='http://localhost:4173';
 await page.goto(origin,{waitUntil:'networkidle'});assert.match(await page.title(),/FoamLab/);await page.screenshot({path:path.join(out,'desktop-home.png'),fullPage:true});
 await page.getByRole('button',{name:'搜索课程、命令、配置…'}).click();await page.locator('#global-search').fill('接触角');await page.locator('#search-results a').first().waitFor();assert((await page.locator('#search-results a').count())>0);await page.keyboard.press('Escape');await page.locator('#search-dialog').waitFor({state:'hidden'});
 await page.goto(origin+'/commands/');await page.locator('#command-query').fill('checkMesh');await page.getByRole('heading',{name:'checkMesh',exact:true}).waitFor();assert((await page.locator('.command-card').count())>0);await page.screenshot({path:path.join(out,'commands.png'),fullPage:true});
 await page.goto(origin+'/dictionaries/');await page.locator('.dictionary-card').first().waitFor();assert.equal(await page.locator('.dictionary-card').count(),53);for(const term of ['locationInMesh','nSurfaceLayers','maxCo']){await page.locator('#dictionary-query').fill(term);assert((await page.locator('.dictionary-card').count())>0,term);}await page.locator('#dictionary-query').fill('snappyHexMeshDict');await page.screenshot({path:path.join(out,'dictionaries.png'),fullPage:true});await page.locator('.dictionary-card').first().click();assert(await page.getByRole('heading',{name:'关键条目索引'}).isVisible());
 await page.goto(origin+'/account/');await page.waitForFunction(()=>window.foamAuth?.ready);await page.evaluate(()=>window.foamAuth.ready);assert(await page.locator('[name=display_name]').isDisabled());assert(await page.locator('#account-shortcuts a').count()===6);await page.screenshot({path:path.join(out,'account.png'),fullPage:true});
 await page.goto(origin+'/lessons/01/');await page.locator('#toc a').first().waitFor();assert((await page.locator('.prose pre code').count())>0);await page.locator('#complete-lesson').click();await page.reload();assert.match(await page.locator('#complete-lesson').textContent(),/已完成/);await page.screenshot({path:path.join(out,'lesson.png'),fullPage:false});
 await page.goto(origin);assert.equal(await page.locator('#progress-count').textContent(),'1');
 // Isolated API fixtures exercise the classroom without creating public issues.
 const fixture=[{number:11,title:'[作业发布] 方腔流动对比',body:'任务要求：比较两个 Re。',user:{login:'MrLittleShark'},state:'open',comments:2,created_at:'2026-10-01T09:00:00Z',html_url:'https://github.com/MrLittleShark/MrLittleShark.github.io/issues/11'},
 {number:12,title:'[作业发布] 非教师发布',body:'must be excluded',user:{login:'student-demo'},state:'open',comments:0,created_at:'2026-10-01T09:00:00Z',html_url:'https://github.com/MrLittleShark/MrLittleShark.github.io/issues/12'},
 {number:13,title:'[提问] 网格问题',body:'<img src=x onerror=alert(1)>',user:{login:'student-demo'},state:'open',comments:1,created_at:'2026-10-01T09:00:00Z',html_url:'https://github.com/MrLittleShark/MrLittleShark.github.io/issues/13'},
 {number:14,title:'[公告] 学习安排',body:'第 01 讲。',user:{login:'MrLittleShark'},state:'open',comments:0,created_at:'2026-10-01T09:00:00Z',html_url:'https://github.com/MrLittleShark/MrLittleShark.github.io/issues/14'},
 {number:15,title:'[作业提交] #11 结果',body:'关联作业：#11',user:{login:'student-demo'},state:'open',comments:0,created_at:'2026-10-01T09:00:00Z',html_url:'https://github.com/MrLittleShark/MrLittleShark.github.io/issues/15'}];
 await page.route('https://api.github.com/repos/**/issues?**',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(fixture)}));
 await page.goto(origin+'/assignments/');await page.locator('.issue-card').waitFor();assert.equal(await page.locator('.issue-card').count(),1);assert(!await page.getByText('非教师发布',{exact:false}).count());
 await page.getByRole('button',{name:'提交此作业'}).click();assert.equal(await page.locator('#student-form [name=subject]').inputValue(),'11');await page.locator('#student-form [name=body]').fill('完成网格、计算与结果验证。');await page.evaluate(()=>{window.open=(url)=>{window.capturedURL=url;return null;};});await page.locator('#student-form button[type=submit]').click();const submitted=new URL(await page.evaluate(()=>window.capturedURL));assert.equal(submitted.hostname,'github.com');assert.match(submitted.searchParams.get('title'),/^\[作业提交\] #11/);assert.match(submitted.searchParams.get('body'),/关联作业：#11/);
 await page.locator('[data-issue-filter="1"]').click();assert.equal(await page.locator('.issue-card').count(),1);assert.match(await page.locator('.issue-card h2').textContent(),/#11/);
 assert.equal(await page.locator('#teacher-tools,#teacher-form').count(),0);
 await page.goto(origin+'/announcements/');await page.locator('.issue-card').waitFor();assert.match(await page.locator('.issue-card h2').textContent(),/学习安排/);
 await page.goto(origin+'/community/');await page.locator('.issue-card').waitFor();assert.equal(await page.locator('.issue-card img').count(),0);await page.locator('[data-issue-filter="2"]').click();assert.equal(await page.locator('.issue-card').count(),0);
 await page.unroute('https://api.github.com/repos/**/issues?**');await page.goto(origin+'/assignments/');await page.waitForFunction(()=>!document.querySelector('#live-status').textContent.includes('正在'));await page.screenshot({path:path.join(out,'assignments-live.png'),fullPage:true});
 // Verify a readable offline/API failure state.
 await page.route('https://api.github.com/repos/**/issues?**',r=>r.fulfill({status:403,body:'{}'}));await page.reload();await page.getByText('公开记录暂时无法加载',{exact:true}).waitFor();assert(await page.locator('#student-form').isVisible());
 const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const m=await mobile.newPage();await m.goto(origin);await m.screenshot({path:path.join(out,'mobile-home.png'),fullPage:true});await m.getByRole('button',{name:'打开导航'}).click();assert(await m.locator('body').evaluate(el=>el.classList.contains('nav-open')));await m.locator('.sidebar a[href="/courses/"]').click();assert.match(m.url(),/courses/);
 const checkRoutes=['/','/courses/','/commands/','/dictionaries/','/dictionaries/system-snappyhexmeshdict/','/account/','/reference/','/resources/','/lessons/01/','/reference/guide-15/','/assignments/','/community/','/announcements/','/lessons/26/','/maintenance/','/admin/'];const overflow=[];
 for(const route of checkRoutes){await m.goto(origin+route,{waitUntil:'domcontentloaded'});if(await m.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1))overflow.push(route);}
 assert.deepEqual(overflow,[],'Mobile horizontal overflow');assert.deepEqual(errors,[],'Browser errors');
 const result={status:'passed',desktop:'1440x1080',mobile:'390x844',checks:['search','command filtering','53 dictionaries and parameter search','guest account state','local progress persistence','trusted teacher filtering','submission prefill','public teacher forms removed','announcement list','question state filters','untrusted HTML escaped','live GitHub read','API error fallback','mobile menu','16 routes without horizontal overflow'],browser_errors:errors};fs.writeFileSync(path.join(out,'browser-check.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
