/* Isolated browser verification: every Supabase request is fulfilled locally.
 * No user credentials, real account tokens, storage writes or public posts used.
 */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require('C:/Users/shark/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const ORIGIN=process.env.FOAM_CHECK_ORIGIN||'http://localhost:4173';
const ROOT=path.resolve(__dirname,'..'),OUT=path.join(ROOT,'.openfoam-work/replan');fs.mkdirSync(OUT,{recursive:true});
const ADMIN='11111111-1111-4111-8111-111111111111',MEMBER='22222222-2222-4222-8222-222222222222';
const now='2026-10-02T01:00:00Z',checks=[];
const content=(id,slug,extra={})=>({id,slug,kind:'article',title:'测试文章 '+slug,summary:'隔离测试资料',body:'### 数据与方程\n\n速度满足 $U=1$。\n\n```foam\napplication icoFoam;\n```',track:'测试主题',series:'测试专栏',status:'published',author_id:ADMIN,author_name:'测试作者',sort_order:1,revision:1,comments_enabled:true,cover_url:'',metadata:{},created_at:now,updated_at:now,...extra});
const jwt=user=>['eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9',Buffer.from(JSON.stringify({sub:user.id,exp:Math.floor(Date.now()/1000)+3600,role:'authenticated'})).toString('base64url'),'test-signature'].join('.');
async function fixture(browser,role='anon',options={}){
 const context=await browser.newContext({viewport:options.mobile?{width:390,height:844}:{width:1440,height:1000},storageState:options.storageState});
 const user=role==='anon'?null:{id:role==='admin'?ADMIN:MEMBER,email:'fixture@example.invalid',aud:'authenticated',role:'authenticated',app_metadata:{provider:'github',providers:['github']},user_metadata:{user_name:'fixture-user'},created_at:now,identities:[]};
 const db={foamlab_content:[content('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','published-fixture'),content('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','member-draft',{author_id:MEMBER,status:'draft'}),content('cccccccc-cccc-4ccc-8ccc-cccccccccccc','member-published',{author_id:MEMBER}),content('dddddddd-dddd-4ddd-8ddd-dddddddddddd','command-fixture',{kind:'reference',metadata:{canonical_path:'/dictionaries/0-alpha-water/'}})],foamlab_profiles:user?[{user_id:user.id,display_name:'测试读者'}]:[],foamlab_public_profiles:[{user_id:ADMIN,display_name:'测试管理员'},{user_id:MEMBER,display_name:'测试会员'}],foamlab_author_levels:[{user_id:ADMIN,level:8},{user_id:MEMBER,level:3}],foamlab_learning_progress:[],foamlab_roles:[{user_id:ADMIN,role:'admin'},...(['blocked','editor','moderator'].includes(role)?[{user_id:MEMBER,role}]:[])],foamlab_settings:[{key:'site',value:{name:'FoamLab',discussion_open:options.closed!==true}}],foamlab_threads:[],foamlab_messages:[],foamlab_revisions:[]};
 for(let i=0;i<(options.topicCount||1);i++)db.foamlab_threads.push({id:'topic-'+i,title:'方腔问题 '+i,body:'具体问题正文与运行记录，包含至少十个有效字符。',category:'使用问题',version:'v2512',status:options.threadClosed?'closed':'open',pinned:false,author_id:MEMBER,created_at:now,updated_at:now});
 for(let i=0;i<(options.replyCount||0);i++)db.foamlab_messages.push({id:'reply-'+i,thread_id:'topic-0',content_id:null,author_id:MEMBER,body:'这是隔离回复 '+i,status:'visible',created_at:now});
 const writes=[],errors=[],files=[];let failContent=false;
 await context.addInitScript(({user,token,persist})=>{if(persist&&localStorage.getItem('fixture-seeded'))return;localStorage.clear();sessionStorage.clear();if(persist)localStorage.setItem('fixture-seeded','1');if(user)localStorage.setItem('foamlab-auth',JSON.stringify({access_token:token,refresh_token:'fixture-refresh',expires_at:Math.floor(Date.now()/1000)+3600,expires_in:3600,token_type:'bearer',user}));},{user,token:user?jwt(user):null,persist:options.persistSession===true});
 await context.route('**/*',async route=>{
  const req=route.request(),url=new URL(req.url());
  const reply=(data,status=200,headers={})=>route.fulfill({status,contentType:'application/json',headers:{'access-control-allow-origin':'*','access-control-expose-headers':'content-range',...headers},body:JSON.stringify(data)});
  if(url.origin===ORIGIN){
   if(url.pathname==='/assets/auth-config.json')return reply({supabaseUrl:'https://cms-fixture.supabase.co',publishableKey:'sb_publishable_fixture'});
   if(['/assets/lab.js','/assets/cms.js','/assets/browser-code.js','/assets/browser-code-worker.js'].includes(url.pathname))return route.fulfill({contentType:'text/javascript',body:fs.readFileSync(path.join(ROOT,'themes/foam-lab/source',url.pathname),'utf8')});
   if(options.reference&&url.pathname==='/dictionaries/0-alpha-water/'){
    const p=path.join(ROOT,'public-openfoam',url.pathname,'index.html');let html=fs.readFileSync(p,'utf8');html=html.replace(/<article class="article"[^>]*>/,'<article class="article" data-cms-slug="command-fixture">');return route.fulfill({contentType:'text/html',body:html});
   }
   return route.continue();
  }
  if(url.hostname!=='cms-fixture.supabase.co')return route.abort();
  if(req.method()==='OPTIONS')return route.fulfill({status:204,headers:{'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,PATCH,PUT,DELETE,HEAD','access-control-allow-headers':'*'}});
  if(url.pathname==='/auth/v1/settings')return reply({external:{github:true}});
  if(url.pathname==='/auth/v1/user')return reply(user||{message:'no session'},user?200:401);
  if(url.pathname.startsWith('/auth/'))return reply({});
  if(url.pathname.startsWith('/storage/')){
   if(url.pathname.includes('/object/list/')){const b=req.postDataJSON();return reply(files.slice(b.offset||0,(b.offset||0)+(b.limit||100)));}
   if(req.method()==='POST'){const name=decodeURIComponent(url.pathname.split('/').pop());files.push({name,metadata:{size:20},created_at:now});writes.push({table:'storage',method:'POST',name});return reply({Key:'foamlab-resources/library/'+name});}
   if(req.method()==='DELETE'){const prefixes=req.postDataJSON().prefixes||[];for(let i=files.length-1;i>=0;i--)if(prefixes.includes('library/'+files[i].name))files.splice(i,1);writes.push({table:'storage',method:'DELETE',prefixes});return reply([]);}return reply({});
  }
  const table=url.pathname.split('/').pop();if(!db[table])return reply({message:'Unknown fixture table '+table},404);
  if(table==='foamlab_content'&&failContent)return reply({message:'fixture network unavailable'},503);
  let data=db[table].filter(row=>{
   if(table==='foamlab_content'&&!['admin','editor'].includes(role)&&!(row.status==='published'||row.author_id===user?.id))return false;
   if(table==='foamlab_roles'&&role!=='admin'&&row.user_id!==user?.id)return false;
   for(const [key,expr]of url.searchParams){if(['select','order','limit','offset','on_conflict'].includes(key))continue;const [op,...parts]=expr.split('.'),value=parts.join('.');if(op==='ov'&&!(row[key]||[]).some(v=>value.slice(1,-1).split(',').includes(v)))return false;if(op==='eq'&&String(row[key])!==value)return false;if(op==='neq'&&String(row[key])===value)return false;if(op==='in'&&!value.slice(1,-1).split(',').map(x=>x.replaceAll('"','')).includes(String(row[key])))return false;if(op==='ilike'&&!String(row[key]).includes(value.replaceAll('%','')))return false;}return true;
  });
  const method=req.method(),prefer=req.headers().prefer||'',single=(req.headers().accept||'').includes('vnd.pgrst.object');
  if(['POST','PATCH','DELETE'].includes(method)){
   const body=method==='DELETE'?null:req.postDataJSON();writes.push({table,method,body});
   if(method==='POST'){
    const inputs=Array.isArray(body)?body:[body];data=inputs.map(input=>{const match=prefer.includes('resolution=merge-duplicates')?db[table].find(x=>(url.searchParams.get('on_conflict')||(table==='foamlab_settings'?'key':'user_id')).split(',').every(key=>x[key]===input[key])):null;if(match){Object.assign(match,input);return match;}const row=table==='foamlab_content'?content(crypto.randomUUID(),input.slug,{status:'draft',...input}):{id:crypto.randomUUID(),created_at:now,status:table==='foamlab_threads'?'open':'visible',...input};db[table].push(row);return row;});
   }else if(method==='PATCH'){data.forEach(row=>{if(table==='foamlab_content'){db.foamlab_revisions.push({id:crypto.randomUUID(),content_id:row.id,revision:row.revision,snapshot:structuredClone(row),created_at:now});Object.assign(row,body,{revision:row.revision+1});}else Object.assign(row,body);});}
   else {const removed=new Set(data);db[table]=db[table].filter(x=>!removed.has(x));}
   if(!prefer.includes('return=representation'))return route.fulfill({status:204,headers:{'access-control-allow-origin':'*'}});
  }
  const ordering=(url.searchParams.get('order')||'').split(',').filter(Boolean);if(ordering.length)data.sort((a,b)=>{for(const term of ordering){const [field,direction]=term.split('.'),x=a[field],y=b[field];const comparison=typeof x==='number'&&typeof y==='number'?x-y:String(x??'').localeCompare(String(y??''));if(comparison)return direction==='desc'?-comparison:comparison;}return 0;});
  const total=data.length,offset=Number(url.searchParams.get('offset')||0),limit=Number(url.searchParams.get('limit')||1000);data=data.slice(offset,offset+limit);
  if(method==='HEAD')return route.fulfill({status:200,headers:{'content-range':`0-${Math.max(0,total-1)}/${total}`,'access-control-allow-origin':'*','access-control-expose-headers':'content-range'}});
  if(single)return data.length===1?reply(data[0]):reply({code:'PGRST116',message:'JSON object requested, multiple (or no) rows returned',details:'The result contains '+data.length+' rows'},406);
  return reply(data,200,{'content-range':`${offset}-${offset+data.length-1}/${total}`});
 });
 if(options.autoConfirm)await context.addInitScript(()=>{new MutationObserver(()=>{document.querySelector('.cms-dialog[open] button[value=confirm]')?.click();}).observe(document,{childList:true,subtree:true});});
 const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 return {context,page,db,writes,errors,files,setFailure:value=>failContent=value,async close(){assert.deepEqual(errors,[],'unhandled browser exceptions');await context.close();}};
}
async function ready(page,path,selector){await page.goto(ORIGIN+path);await page.locator(selector).first().waitFor({state:'visible'});}
async function waitFor(page,predicate){await page.waitForFunction(predicate);}
module.exports={fixture,ready,content,ORIGIN,ROOT,OUT,ADMIN,MEMBER};
if(require.main===module)(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 try{
  const admin=await fixture(browser,'admin',{autoConfirm:true});const p=admin.page;
  await ready(p,'/admin/','#cms-new');await p.click('#cms-new');
  await p.locator('#cms-advanced').evaluate(e=>e.open=true);await p.locator('[name=title]').fill('新建审核课程');await p.locator('[name=slug]').fill('Bad slug');assert.equal(await p.locator('[name=slug]').evaluate(e=>e.checkValidity()),false);await p.locator('[name=slug]').fill('new-course-fixture');await p.locator('[name=body]').fill('### 可复核计算\n\n方程 $a^2+b^2=c^2$。\n\n```bash\necho "$WM_PROJECT_VERSION"\n```');
  await p.click('#cms-publish-now');await p.waitForFunction(()=>document.querySelector('#cms-notice')?.textContent.includes('已发布'));
  assert.equal(admin.db.foamlab_content.find(x=>x.slug==='new-course-fixture').status,'published');
  await p.click('#cms-preview-button');assert.equal(await p.locator('#cms-preview .katex').count(),1);assert.equal(await p.locator('#cms-preview .code-panel').count(),1);
  const id=admin.db.foamlab_content.find(x=>x.slug==='new-course-fixture').id;
  await p.click(`#cms-editor [data-trash="${id}"]`);await p.waitForSelector(`[data-restore="${id}"]`);assert.equal(admin.db.foamlab_content.find(x=>x.id===id).status,'trash');await p.click(`[data-restore="${id}"]`);await p.waitForFunction(()=>!document.querySelector('#cms-root')?.hasAttribute('aria-busy'));assert.equal(admin.db.foamlab_content.find(x=>x.id===id).status,'draft');
  await p.click(`[data-edit="${id}"]`);await p.locator('[name=title]').fill('保留冲突稿件');admin.db.foamlab_content.find(x=>x.id===id).revision++;await p.click('#cms-edit-form [type=submit]');await p.waitForFunction(()=>document.querySelector('#cms-notice')?.textContent.includes('其他编辑'));assert.equal(await p.locator('[name=title]').inputValue(),'保留冲突稿件');checks.push('admin create/publish/trash/restore/revision conflict');
  await p.locator('#cms-more').evaluate(e=>e.open=true);await p.click('[data-cms-tab=roles]');await p.locator('#cms-role-form [name=user_id]').fill(MEMBER);await p.locator('#cms-role-form [name=role]').selectOption('editor');await p.click('#cms-role-form button');await p.waitForFunction(()=>document.querySelector('#cms-notice')?.textContent.includes('已保存'));assert.equal(admin.db.foamlab_roles.find(r=>r.user_id===MEMBER).role,'editor');await p.click(`[data-remove-role="${MEMBER}"]`);await p.waitForFunction(()=>document.querySelector('#cms-notice')?.textContent.includes('普通会员'));checks.push('role management refresh without function shadowing');
  await p.click('[data-cms-tab=files]');await p.setInputFiles('#cms-upload',{name:'example.txt',mimeType:'text/plain',buffer:Buffer.from('fixture resource')});await p.waitForSelector('[data-create-resource]');await p.click('[data-create-resource]');await p.waitForSelector('#cms-edit-form');assert.equal(await p.locator('[name=kind]').inputValue(),'resource');checks.push('resource upload and draft creation');
  await p.evaluate(()=>scrollTo(0,0));await p.screenshot({animations:'disabled',path:path.join(OUT,'cms-admin-verified.png'),fullPage:true});await admin.close();

  const member=await fixture(browser,'member',{mobile:true});await ready(member.page,'/studio/','#cms-new');assert.equal(await member.page.locator('[data-trash]').count(),0);assert.equal(await member.page.locator('.cms-title-button[data-edit]').count(),2);assert.equal(await member.page.locator('.cms-stats strong').first().textContent(),'2');await member.page.click('#cms-new');assert.equal(await member.page.locator('[name=status] option').count(),2);assert.equal(await member.page.locator('#cms-publish-now').count(),1);await member.page.locator('#cms-advanced').evaluate(e=>e.open=true);assert.deepEqual(await member.page.locator('[name=kind] option').evaluateAll(a=>a.map(x=>x.value)),['article','log']);
  await member.page.locator('[name=title]').fill('会员投稿测试');await member.page.locator('[name=slug]').fill('member-new');await member.page.locator('[name=body]').fill('这是完整的会员草稿。');await member.page.click('#cms-edit-form [type=submit]');await member.page.waitForFunction(()=>document.querySelector('#cms-notice')?.textContent.includes('已保存'));assert.equal(member.db.foamlab_content.find(r=>r.slug==='member-new').status,'draft');
  await member.page.locator('#cms-publish-now').click();await member.page.waitForFunction(()=>document.querySelector('#cms-notice')?.textContent.includes('已发布'));assert.equal(member.db.foamlab_content.find(r=>r.slug==='member-new').status,'published');
  await member.page.evaluate(()=>{const select=document.querySelector('[name=kind]');select.add(new Option('课程','lesson'));select.value='lesson';});await member.page.click('#cms-edit-form [type=submit]');await member.page.waitForFunction(()=>document.querySelector('#cms-notice')?.textContent.includes('个人工作台'));assert.equal(member.db.foamlab_content.find(r=>r.slug==='member-new').kind,'article');assert.equal(await member.page.locator('#cms-history').count(),0);assert(await member.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));await member.page.screenshot({path:path.join(OUT,'cms-member-mobile.png'),fullPage:true});checks.push('member own article draft/publish/edit; protected content kinds; mobile layout');await member.close();

  const anon=await fixture(browser,'anon');await ready(anon.page,'/sharing/','.lab-card');assert.equal(await anon.page.locator('.lab-card img').count(),0);assert(await anon.page.locator('.lab-card-mark').count()>0);await ready(anon.page,'/read/?slug=published-fixture','#lab-comments');assert.equal(await anon.page.locator('.lab-reply-form [data-lab-login]').count(),1);
  const result=await anon.page.evaluate(()=>{window.__fixtureXSS=false;const h=document.createElement('div');h.innerHTML=FoamLab.markdown('<img src="x" onerror="window.__fixtureXSS=true"><script>window.__fixtureXSS=true</script><a href="javascript:alert(1)" data-topic-id="target" data-state="hidden">x</a><textarea name="body">spoof</textarea>\n\n$U=1$\n\n<code>$HOME$</code>');document.body.append(h);return {script:h.querySelectorAll('script,[onerror],textarea,[data-topic-id],[data-state]').length,math:h.querySelectorAll('.katex').length,code:h.querySelector('code')?.textContent,unsafe:[...h.querySelectorAll('a')].some(a=>a.href.startsWith('javascript:')),empty:FoamLab.safeURL(''),missing:FoamLab.safeURL(undefined)};});assert.deepEqual(result,{script:0,math:1,code:'$HOME$',unsafe:false,empty:'',missing:''});checks.push('anon read, login gate, Markdown XSS and event-gadget filtering, TeX and raw code');await anon.close();

  const editor=await fixture(browser,'editor');await ready(editor.page,'/admin/','#cms-new');assert.equal(await editor.page.locator('[data-cms-tab=roles]').count(),0);assert.equal(await editor.page.locator('[data-cms-tab=content]').count(),1);await editor.page.click('#cms-new');await editor.page.locator('#cms-advanced').evaluate(e=>e.open=true);await editor.page.locator('[name=title]').fill('编辑工作区：数值格式与可复现实验');await editor.page.locator('[name=slug]').fill('editor-preview');await editor.page.locator('[name=body]').fill('## 算法与配置\n\n\\[\\nabla\\cdot\\mathbf{U}=0\\]\n\n```cpp\nconst scalar dt = runTime.deltaTValue();\nInfo << dt << endl;\n```');await editor.page.click('#cms-preview-button');await editor.page.locator('#cms-preview pre').scrollIntoViewIfNeeded();await editor.page.waitForSelector('#cms-preview .hljs-type');await editor.page.click('#cms-preview [data-lab-wrap]');assert(await editor.page.locator('#cms-preview .code-panel').evaluate(e=>e.classList.contains('wrap-lines')));await editor.page.evaluate(()=>scrollTo(0,0));await editor.page.screenshot({animations:'disabled',path:path.join(OUT,'cms-editor-verified.png'),fullPage:true});await editor.page.setViewportSize({width:390,height:844});assert(await editor.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));await editor.page.screenshot({animations:'disabled',path:path.join(OUT,'cms-editor-mobile.png'),fullPage:true});checks.push('editor controls; dynamic C++ worker highlighting, code wrapping, mobile editor');await editor.close();

  const progress=await fixture(browser,'member');progress.db.foamlab_content=Array.from({length:46},(_,i)=>content(`00000000-0000-4000-8000-${String(i+1).padStart(12,'0')}`,'lesson-'+i,{kind:'lesson'}));progress.db.foamlab_content.push(content('99999999-9999-4999-8999-999999999999','archived-lesson',{kind:'lesson',status:'archived',author_id:MEMBER}));progress.db.foamlab_learning_progress=[0,1].map(i=>({user_id:MEMBER,content_id:progress.db.foamlab_content[i].id,completed:true}));progress.db.foamlab_learning_progress.push({user_id:MEMBER,content_id:'99999999-9999-4999-8999-999999999999',completed:true});await ready(progress.page,'/account/','#account-name');await progress.page.waitForFunction(()=>document.querySelector('#account-progress-state')?.textContent.includes('2 / 46'));assert.equal(await progress.page.locator('#account-completed').textContent(),'2');await ready(progress.page,'/read/?slug=lesson-2','#lab-complete');await progress.page.click('#lab-complete');await progress.page.waitForFunction(()=>document.querySelector('#lab-complete')?.textContent.includes('已学完'));assert(progress.db.foamlab_learning_progress.some(r=>r.content_id===progress.db.foamlab_content[2].id&&r.completed));await progress.page.goto(ORIGIN+'/account/');await progress.page.waitForFunction(()=>document.querySelector('#account-progress-state')?.textContent.includes('3 / 46'));assert.equal(progress.writes.filter(r=>r.table==='foamlab_progress').length,0);const rejected=await progress.page.evaluate(async()=>{try{await FoamLab.recordCompletion(3,true);return false;}catch{return true;}});assert(rejected);checks.push('46 UUID lesson progress persisted after navigation; archived and legacy numbers excluded');await progress.close();

  const nav=await fixture(browser,'anon',{mobile:true});nav.db.foamlab_content=[content('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','nav-a',{kind:'lesson',series:'导航测试课程',sort_order:10}),content('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','nav-b',{kind:'lesson',series:'导航测试课程',sort_order:20}),content('cccccccc-cccc-4ccc-8ccc-cccccccccccc','nav-c',{kind:'lesson',series:'导航测试课程',sort_order:30}),content('dddddddd-dddd-4ddd-8ddd-dddddddddddd','other-series',{kind:'lesson',series:'另一课程',sort_order:1})];await ready(nav.page,'/read/?slug=nav-a','.chapter-controls');assert(await nav.page.locator('[data-chapter=first]').isDisabled());assert(await nav.page.locator('[data-chapter=previous]').isDisabled());assert.equal(await nav.page.locator('[data-chapter=next]').getAttribute('href'),'/read/?slug=nav-b');assert.equal(await nav.page.locator('[data-chapter=last]').getAttribute('href'),'/read/?slug=nav-c');assert.equal(await nav.page.locator('.chapter-heading strong').textContent(),'第 1 / 3 章');await nav.page.click('[data-chapter=next]');await nav.page.waitForFunction(()=>document.querySelector('.chapter-heading strong')?.textContent==='第 2 / 3 章');nav.db.foamlab_content[1].sort_order=5;nav.db.foamlab_content[1].title='后台重命名后的首章';await nav.page.reload();await nav.page.waitForFunction(()=>document.querySelector('.chapter-heading strong')?.textContent==='第 1 / 3 章');nav.db.foamlab_content[2].status='archived';await nav.page.click('[data-chapter=next]');await nav.page.waitForFunction(()=>document.querySelector('.chapter-heading strong')?.textContent==='第 2 / 2 章');assert(await nav.page.locator('[data-chapter=next]').isDisabled());assert(await nav.page.locator('[data-chapter=last]').isDisabled());assert((await nav.page.locator('.chapter-neighbors').textContent()).includes('后台重命名后的首章'));await nav.page.addStyleTag({path:path.join(ROOT,'themes/foam-lab/source/assets/lesson-navigation.css')});await nav.page.locator('.lesson-navigation').scrollIntoViewIfNeeded();assert(await nav.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));await nav.page.screenshot({animations:'disabled',path:path.join(OUT,'lesson-navigation-mobile.png')});checks.push('first/previous/next/last navigation; series isolation; live ordering/title/archive changes; mobile');await nav.close();

  const large=await fixture(browser,'anon');await ready(large.page,'/read/?slug=published-fixture','#lab-comments');await large.page.locator('.prose pre').scrollIntoViewIfNeeded();await large.page.waitForSelector('.prose .hljs-keyword');const largeResult=await large.page.evaluate(async()=>{const target=document.createElement('div'),code='Info << "<script>" << endl;\n'.repeat(5000);target.innerHTML=FoamLab.markdown('```cpp\n'+code+'```');document.body.append(target);await new Promise(r=>setTimeout(r,80));const node=target.querySelector('code');return {mode:node.dataset.foamHighlight,unchanged:node.textContent.trimEnd()===code.trimEnd(),injected:target.querySelectorAll('script').length};});assert.deepEqual(largeResult,{mode:'plain',unchanged:true,injected:0});checks.push('large code blocks remain intact plain text without worker parsing or HTML injection');await large.close();

  const forum=await fixture(browser,'member',{topicCount:205,replyCount:205});await ready(forum.page,'/community/','#forum-more');assert.equal(await forum.page.locator('.lab-topic-row').count(),200);await forum.page.click('#forum-more');await forum.page.waitForFunction(()=>document.querySelectorAll('.lab-topic-row').length===205);await ready(forum.page,'/community/?topic=topic-0','.lab-message-more');assert.equal(await forum.page.locator('h1').count(),1);assert.equal(await forum.page.locator('.lab-message').count(),200);await forum.page.locator('.lab-reply-form textarea').fill('保留尚未提交的回复');await forum.page.click('.lab-message-more');await forum.page.waitForFunction(()=>document.querySelectorAll('.lab-message').length===205);assert.equal(await forum.page.locator('.lab-reply-form textarea').inputValue(),'保留尚未提交的回复');await forum.page.locator('.lab-reply-form textarea').fill('这是新增的公开回答及验证方法。');await forum.page.click('.lab-reply-form [type=submit]');await forum.page.waitForFunction(()=>!document.querySelector('.lab-reply-form [type=submit]')?.disabled);assert(forum.db.foamlab_messages.some(x=>x.body.includes('新增的公开回答')));checks.push('forum and replies pagination beyond 200; draft preserved; reply publication');await forum.close();
  const closed=await fixture(browser,'member',{closed:true});await ready(closed.page,'/community/','#new-topic');assert(await closed.page.locator('#new-topic').isDisabled());checks.push('discussion switch disables new topic');await closed.close();
  const locked=await fixture(browser,'member',{threadClosed:true});await ready(locked.page,'/community/?topic=topic-0','.lab-reply-form');assert.equal(await locked.page.locator('.lab-reply-form textarea').count(),0);checks.push('closed thread has no reply form');await locked.close();

  const ref=await fixture(browser,'anon',{reference:true});await ready(ref.page,'/dictionaries/0-alpha-water/','#cms-reference-comments');assert.match(await ref.page.locator('.article h1').textContent(),/测试文章 command-fixture/);assert.equal(await ref.page.locator('#toc a').count(),1);ref.db.foamlab_content.find(r=>r.slug==='command-fixture').status='archived';await ref.page.reload();await ref.page.waitForFunction(()=>document.querySelector('.article h1')?.textContent==='内容已归档或尚未发布');assert.equal(await ref.page.locator('#toc a').count(),0);ref.setFailure(true);await ref.page.reload();await ref.page.waitForFunction(()=>document.querySelector('.lab-cms-state')?.textContent.includes('缓存版本'));assert(!(await ref.page.locator('.article h1').textContent()).includes('已归档'));checks.push('static CMS override, comments, archive, network fallback');await ref.close();
  fs.writeFileSync(path.join(OUT,'cms-ui-check.json'),JSON.stringify({checks,passed:checks.length,externalWrites:0},null,2));console.log(JSON.stringify({passed:checks.length,checks,externalWrites:0},null,2));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
