const {chromium}=require('C:/Users/shark/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const user={id:'00000000-0000-4000-8000-000000000001',aud:'authenticated',role:'authenticated',user_metadata:{user_name:'fixture-user',full_name:'测试学习者'},app_metadata:{provider:'github'},created_at:'2026-01-01T00:00:00Z'};
const b64=x=>Buffer.from(JSON.stringify(x)).toString('base64url');const token=b64({alg:'HS256',typ:'JWT'})+'.'+b64({sub:user.id,exp:Math.floor(Date.now()/1000)+3600,role:'authenticated'})+'.fixture-not-a-real-signature';
const session={access_token:token,refresh_token:'fixture-not-a-real-token',expires_at:Math.floor(Date.now()/1000)+3600,expires_in:3600,token_type:'bearer',user};
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});let profile={user_id:user.id,display_name:'测试学习者',institution:'',research:'',level:'beginner',bio:'',shortcuts:['courses','commands']},progress=[{lesson_id:2,completed:true}];let rejectUser=false,failData=false;const errors=[];
async function create(){const c=await browser.newContext();await c.addInitScript(s=>localStorage.setItem('foamlab-auth',JSON.stringify(s)),session);const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));await p.route('https://nmkforbzmbstasnjxlid.supabase.co/**',async route=>{const req=route.request(),u=new URL(req.url());let body={},status=200;if(u.pathname==='/auth/v1/settings')body={external:{github:true}};else if(u.pathname==='/auth/v1/user'){body=rejectUser?{message:'Invalid token',code:'bad_jwt'}:user;status=rejectUser?401:200;}else if(u.pathname.startsWith('/rest/v1/')){if(failData){status=503;body={message:'Fixture unavailable'};}else if(u.pathname.endsWith('foamlab_profiles')){if(req.method()==='GET')body=profile;else {profile=req.postDataJSON();body=null;}}else if(u.pathname.endsWith('foamlab_progress')){if(req.method()==='GET')body=progress;else {const data=req.postDataJSON();for(const row of Array.isArray(data)?data:[data]){progress=progress.filter(x=>x.lesson_id!==row.lesson_id);progress.push(row);}body=null;}}else status=404;}else status=404;await route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)});});return p;}
const a=await create();await a.goto('http://localhost:4173/account/');await a.evaluate(()=>window.foamAuth.ready);assert.equal(await a.locator('#account-name').textContent(),'测试学习者');assert.equal(await a.locator('#account-completed').textContent(),'1');await a.locator('[name=display_name]').fill('跨设备测试');await a.locator('[name=institution]').fill('流体研究组');await a.locator('[name=shortcuts][value=dictionaries]').check();await a.getByRole('button',{name:'保存个人资料',exact:true}).click();await a.getByText('个人资料已保存到账号。',{exact:true}).waitFor();assert.equal(profile.institution,'流体研究组');assert.equal(await a.locator('#account-shortcuts a').count(),3);
await a.goto('http://localhost:4173/lessons/01/');await a.evaluate(()=>window.foamAuth.ready);await a.locator('#complete-lesson').click();await a.waitForFunction(()=>window.foamAuth.progress.includes(1));assert(progress.some(x=>x.lesson_id===1&&x.completed));
const b=await create();await b.goto('http://localhost:4173/account/');await b.evaluate(()=>window.foamAuth.ready);assert.equal(await b.locator('#account-name').textContent(),'跨设备测试');assert.equal(await b.locator('#account-completed').textContent(),'2');
failData=true;await b.reload();await b.evaluate(()=>window.foamAuth.ready);assert(await b.locator('[name=display_name]').isDisabled());assert.equal(await b.locator('#account-completed').textContent(),'—');assert.match(await b.locator('#account-state').textContent(),/暂时不可用/);
rejectUser=true;failData=false;const invalid=await create();await invalid.goto('http://localhost:4173/account/');await invalid.evaluate(()=>window.foamAuth.ready);assert.equal(await invalid.locator('#account-name').textContent(),'尚未登录');assert(await invalid.locator('[name=display_name]').isDisabled());assert.deepEqual(errors,[]);
const result={status:'passed',mode:'isolated HTTP fixtures; not a real OAuth login',checks:['server-verified identity','profile save','shortcut selection','account progress write','separate-browser data read','data outage state','unverified session rejected'],errors};fs.writeFileSync(path.join(__dirname,'../.openfoam-work/account-check.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));await browser.close();})().catch(e=>{console.error(e);process.exit(1);});
